### PR TITLE
Update hide_whitelist.txt

### PR DESCRIPTION
**Pull request by JohnyP36**
There were a bunch of filters I couldn't reproduce anymore and after I year of surfing the web I also came along some sites where elements got blocked because of general rules in EasyList that shouldn't be blocked on those domains.

### CODE REVIEW

**Comment by Khrin** [comment]
A reference links for each new filter would be really appreciated, if not required...

**Comment by JohnyP36** [comment]
### L1 
`ajaxreport.nl,blockchainvandaag.com,casinoreport.nl,cryptobelegging.com,feyenoordreport.nl,formula1report.com,gamblingreport.nl,livestreamvandaag.be,onlinecasinorss.nl,onlinekraslotenrss.nl,onlinepokerrss.nl,psvreport.nl,sportweddenrss.nl,vergelijkbookmakers.nl,voetbalsnafu.nl,voetbalvisie.com,voetbalweddenrss.nl#@#.top-ads-block` 

This domains are all the same, so I will only include a screenshot of `ajaxreport.nl`. 
#### URL 
`ajaxreport.nl` *(the homepage of this site)*
#### Screenshot(s)
<details>
<summary>Screenshot 1</summary>

image

</details>
<details>
<summary>Screenshot 2</summary>

image

</details>

#### Problem 
The banner on top of those sites with the site logo gets unrightfully blocked. 

----

### L2 
`dagelijksestandaard.nl#@#.wpInsertInPostAd` 

#### URL 
`https://www.dagelijksestandaard.nl/2022/01/pieter-omtzigt-pakt-rivm-aan-aantal-positief-geteste-volledig-gevaccineerden-wordt-zomaar-omhoog-bijgesteld/`
#### Screenshot(s)
<details>
<summary>Screenshot </summary>

image
</details>

#### Problem 
A row under the article showing other articles you could read (from the same domain) gets blocked. 

I think you also need to add the rules 
```
@@||widgets.spklw.com/v1/data/$xmlhttprequest,domain=dagelijksestandaard.nl
@@||widgets.sprinklecontent.com/v2/$xmlhttprequest,domain=dagelijksestandaard.nl
``` 
<pr>
otherwise you will still see nothing because of the third-party domain `widgets.spklw.com` and `widgets.sprinklecontent.com` 
that are being blocked. 

---- 

### L3 
`directwonen.nl#@#.top-advert` 

#### URL 
`https://directwonen.nl/huurwoningen-huren/rotterdam` 

#### Screenshot(s)
<details>
<summary>Screenshot </summary>

image
</details>

#### Problem 
Many rooms and apartments have a label such as "smart only". But the label "topwoning" gets blocked, which is in my eyes not right. 

---- 

### L4 
`gratisaftehalen.nl#@#.ads-image` 

#### URL 
`https://www.gratisaftehalen.nl/a/redwing-laarzen-gratis-af-te-halen-maat-38-208204?idCategory=139` 

#### Screenshot(s)
<details>
<summary>Screenshot </summary>

image
</details>

#### Problem 
The pictures are blocked and thus brakes up the site, because you need the to see.

---- 

### L5 
`lesoir.be#@##ultimedia_wrapper` 

#### URL 
`https://www.lesoir.be/` *(homepage)* 

#### Screenshot(s)
<details>
<summary>Screenshot </summary>

image
</details>

#### Problem 
The box with videos gets blocked. 
**Note**: the language of this site is french.

---- 

### L6 
`marktplaats.nl#@#.adSummary` 

#### URL 
``

#### Screenshot(s)
 *None*

#### Problem 
I couldn't find the element `.adSummary` on marktplaats.nl now, but last summer when I checked I had found it. 
So it's up to you.

---- 

### L7 
`modekoninginmaxima.nl#@#.after-content-ad` 

#### URL 
`http://www.modekoninginmaxima.nl/mode-maxima-mode-algemeen/dit-maximas-winnende-outfit-van-2021` 

#### Screenshot(s)
<details>
<summary>Screenshot </summary>

image
</details>

#### Problem 
The note (that it is forbidden to copy content from this site) gets blocked.

---- 

I couldn't reproduce `bokt.nl#@#.node-ad` & `bokt.nl#@#.ad-body` anymore.

**Comment by Khrin** [comment]
If `lesoir.be` is only in French language, then must be reported to the respective list https://github.com/easylist/listefr

Only sites in Dutch language here

**Comment by JohnyP36** [comment]
> If `lesoir.be` is only in French language, then must be reported to the respective list https://github.com/easylist/listefr
> 
> Only sites in Dutch language here

I have removed it now.

**Comment by Khrin** [comment]
The removed filters were actually still needed.

I have added some of your proposed filters.

**Pull request closed without merging**
